#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

language: python
python:
  - "3.5"
sudo: required
dist: trusty

services:
  - docker

addons:
  # https://docs.travis-ci.com/user/firefox/
  # https://muffinresearch.co.uk/using-the-latest-version-of-firefox-in-travis-ci/
  firefox: latest
  apt:
    sources:
      # http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/
      - google-chrome
    packages:
      - google-chrome-stable
      # - google-chrome-beta

  # https://docs.travis-ci.com/user/sauce-connect/
  sauce_connect:
    username: "jdanekrh"
    access_key:
      secure: "dRLcC1JYrl0tnwIKBqPixuR9pbpGdJJB7oDzj1dr56FfXuu8+JTyy+Tvsz7OBE7EDreuxOPV5Yd5v/+DF+iw9+1QHTjenfFD0Qj79cm+8tyjESBeKuD11SCEyKMksySbF3RShOdsof3W08uPg/Jlowxel1VtUWRVY54Ht8svLg/aigVtM1Px1XME1kIXav1n6nQvUsdA8nnCfqagh6ctGQcmjBVJqskYPl8jyMuovFKnnZ8hCpq5vMMxIhsahdEzwvU1RI20Sci9Fc7B2ux6jFX0JqYR7t/HrskMVNS4lBcH/JHVb+7L96W1bUXgTb1xrZyKdgyE+PM1Lcx7jxV23wU5x4K7Sl6olIwE9qXJDXW3e4tsxjeR+PFU/duiq85ezgTimsZGNISGSaNenYI+PMTeLjfDdgw19eT8X8j26pAnQ5K/pydsNahlwpXRoF2iz4x5WOgNGjHnhuDOUR376S0DbV1GGnq7d5Yzu2JH5VjnaXSbY8kD42i1Uxfiod/4YtSqmDJGdH4Nha0DLVE5gYgXhRs3qPndf6Prw6lKTZ/Q0Awj19HVXEX4M1Ht4kfLojUAPCpclcK4fIWW73mzfyfNBQutDaw+H4NHE4AzrOHNdVOGH94q6RYa8rmKMKtBksF7kMfbBg2IC/jZb2vLhb/4ys48Ceno8Uxd8ETDMX4="
    no_ssl_bump_domains: "127.0.0.1,localhost"

# https://github.com/travis-ci/travis-web/blob/15dc5ff92184db7044f0ce3aa451e57aea58ee19/.travis.yml
env:
  global:
    - "SAUCELABS_USERNAME=jdanekrh"
    - secure: "lkyhDfP1TvTmAy9eu5gRtyCJZoOeVmsfNByCHeR/POMWsBoh4Ad7zIaMGNYtXIU+7YDxeOnVIwm6dheR1mOu3eVMrCpPhS8wkP4SVeA8/tn+tQd4SB1YAmrDGnhKOVtSNTJLsC4/CSabKnUyN+he75vuzdVmvpWFmItZ3dbl2rc9UVO8WoqasgW/YJejJu5dHZ3RjvUfyROaTMgp4HXjR0WtsHhZDiA7qEvboC9P8tWZ83V2qUr3JThGRwkgpTYLMa1QplcafLjWzsOgZ2HNP/FjqEcYnT0C8LgaVkhZ3LtvTZRML7BPFYmWz1Y6nHj3ra2CJv6PCjTyTyB9McKu29vjo7wQgdUC9wqDWVdXb8oKx0wC4DkNRIXbY2MN786G4IbUq2bWOh5FCJ2yjRlt/sid3E4NyC9U6Jsq0ywqU2PZDrXyWcjHFG90XsUMcwVkTQkdMPQcOz7A6HQ5OgioteB4chrJYWb969CCJZfRrA39EQ5uP1JdF4o/pV4jfDAVbnDvkJPxHCmS5Q42qQxlE5cfpDpRIZkJ87VgTx2yqlL0LD+xcVcDViURk85OYoH5qclJ+IqHe4qhxh8IkSNej4nbrQ5ykcitu+LoN9mAXBdCXMnqO0vONVAP+pA4FTGVSqx3B+ZqGwTxanJnahQn1YZpmfGAe9P7FP2UzyvmOBg="
    # https://github.com/SeleniumHQ/docker-selenium/issues/87
    - "DBUS_SESSION_BUS_ADDRESS=/dev/null"
    - "IMAGE_TAG=10-6a1e663"
  matrix:
    - "CONSOLE=hawtio DRIVER=Chrome PLATFORM=any BROWSER_NAME=any VERSION=any"
    - "CONSOLE=hawtio DRIVER=Firefox PLATFORM=any BROWSER_NAME=firefox VERSION=any"
    - "CONSOLE=stand-alone DRIVER=Chrome PLATFORM=any BROWSER_NAME=any VERSION=any"
    - "CONSOLE=stand-alone DRIVER=Firefox PLATFORM=any BROWSER_NAME=firefox VERSION=any"
    - "CONSOLE=hawtio DRIVER=SauceLabs PLATFORM='Windows 8' BROWSER_NAME='internet explorer' VERSION='10.0'"
    - "CONSOLE=stand-alone DRIVER=SauceLabs PLATFORM='Windows 10' BROWSER_NAME='internet explorer' VERSION='10.0'"

before_install:
  # https://docs.travis-ci.com/user/docker/
  - docker pull jdanekrh/dispatch-console:${IMAGE_TAG}
  - docker pull jdanekrh/dispatch-router:${IMAGE_TAG}
  - docker run -d -p 127.0.0.1:8080:8080 jdanekrh/dispatch-console:${IMAGE_TAG}
  - docker run -d -p 127.0.0.1:5673:5673 jdanekrh/dispatch-router:${IMAGE_TAG}
  - docker ps -a
  # https://github.com/vadesecure/test-automation-framework/blob/66c29c58cdc219c9fe9bd702a7d1784c34b913ce/.travis.yml
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - curl -L -O "https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-linux64.tar.gz"
  - tar -xvf geckodriver-*
  - export PATH=$PATH:$PWD

install:
  - pip install -r requirements.txt

# https://docs.travis-ci.com/user/gui-and-headless-browsers/
# https://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647
before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - bash ./scripts/travis.sh
